import Head from 'next/head'

export default function HomePage() {
  return (
    <div>
      <Head>
        <title>GovStack testing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p>GovStack</p>
      </main>
    </div>
  )
}
