import React from 'react';
import Head from 'next/head';
import ProductTable from '../components/table/ProductTable';

const HomePage = () => {
  return (
    <div>
      <Head>
        <title>GovStack testing</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <ProductTable />
      </main>
    </div>
  );
};

export default HomePage;
