import React from 'react';
import Head from 'next/head';
import { useCallback } from 'react';
import { useIntl } from 'react-intl';
import MainLayout from '../components/mainLayout/MainLayout';

const HomePage = () => {
  const { formatMessage } = useIntl();
  const format = useCallback((id: string) => formatMessage({ id }), [formatMessage]);

  return (
    <div>
      <Head>
        <title>GovStack testing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MainLayout>
          {/* to remove while first children implement */}
          <p>{format('app.title')}</p>
        </MainLayout>
      </main>
    </div>
  );
};

export default HomePage;
